# @package _global_
trainer:
  checkpoint_callback: False
  logger:
    _target_: code.loggers.TensorBoardLogger
    save_dir: ${run.dir}
extra_callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${run.dir}/default/checkpoints
  - _target_: code.callbacks.LossItemsLogCallback
    log_every: 10 seconds