# @package _global_
logger:
  _target_: utils.loggers.TensorBoardLogger
  save_dir: ${run.dir}
extra_callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${run.dir}/default/checkpoints