# @package _global_
device:
  data_root: /var/scratch/{oc.env:USER}/data
  big_data_root: /var/scratch/{oc.env:USER}/data
  experiments_root: /var/scratch/{oc.env:USER}
  download_files: true
  num_workers: 32
  pin_memory: True

trainer:
  gpus: 4
