defaults:
  - device: ${oc.env:DEVICE_NAME}
  - trainer: default
  - logging: wandb

callbacks: []

run:
  name: null
  dir: ${device.experiments_root}/experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${run.dir}