defaults:
  - device: ${oc.env:DEVICE_NAME}
  - logging: wandb

callbacks: []

trainer:
  _target_: pytorch_lightning.Trainer

run:
  name: null
  dir: ${device.experiments_root}/experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${run.dir}